name: Run Appium Tests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (or any version you require)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "temurin"
          cache: maven

      # Step 3: Run Appium Tests with Maven, passing secrets as Maven properties
      - name: Run Appium Tests
        run: mvn clean test -Dusername=${{ secrets.USERNAME }} -Dpassword=${{ secrets.PASSWORD }}
