name: Run Appium Tests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Java 11 (or the version your project requires)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "temurin"
          cache: maven

      # Step 3: Run Appium tests with Maven, passing secrets as environment variables
      - name: Run Appium Tests
        run: mvn clean test  # Runs tests with Maven
        env:
          USERNAME: ${{ secrets.USERNAME }}  # Pass GitHub secret for username
          PASSWORD: ${{ secrets.PASSWORD }}  # Pass GitHub secret for password
